
import "./globals.css";



export const metadata = {
  title: "About page in demo next app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const links = [
    {link: '/', title: 'Home'},
    {link: '/about', title: 'about'},
    {link: '/contact', title: 'Contact'}
  ]
  return (
    <html lang="en">
      <body className="max-w-[1000px] mx-auto" 
      >
        
        <nav className="max-w-50 mx-auto w-full max-w-1000px">
          <ul className={"flex flex-row justify-center py-4 gap-15"}>
            {links.map((link) => (
              <li key={link.title}>
                <a href={link.link} className=" px-4 py-2 border border-black rounded-full">
                  {link.title}
                </a>
              </li>
            ))}
          </ul>
        </nav>
        
       
        {children}
      </body>
    </html>
  );
}
